webinterface/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webinterfaceapp.urls'), )
]

webinterfaceapp/urls.py
from django.urls import path

from webinterfaceapp.views import views

app_name = 'webinterfaceapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('register/', views.registration, name='register'),
    path('pca/', views.pca, name='pca'),
    path('twitter_analysis/', views.twitter, name='twitter_analysis'),
    path('twitter/', views.twitter_response, name='twitter'),
    path('news_analysis/', views.news, name='news_analysis'),
    path('news/', views.news_response, name='news'),
    path('stock_analysis/', views.stock, name='stock_analysis'),
    path('stock/', views.stock_response, name='stock'),
    path('stock-compare/', views.stock_compare_response, name='stock-compare'),
    path('stop/', views.stop_processing, name='stop'),
    path('about/', views.about_us, name='about_us'),
    path('contact/', views.contact_us, name='contact_us'),
    path('twitter_analytics/', views.twitter_analytics, name='twitter_analytics'),
    path('news_analytics/', views.news_analytics, name='news_analytics'),
    path('stock_analytics/', views.stock_analytics, name='stock_analytics'),
    path('facebook_analysis/', views.facebook, name='facebook_analysis'),
    path('facebook_analytics/', views.facebook_analytics, name='facebook_analytics'),
    path('google_search_trend/', views.google_search_trend, name='google_search_trend'),
    path('google_search/', views.google_search, name='google_search')
]

webinterfaceapp/models.py
from django.db import models
from django.db import connection, connections
import json


def ValidateLogin(user,password):
    if(user == 'admin' and password == '1234'):
        return True
    else:
        return False


class TwitterData(models.Model):
    text = models.TextField(max_length=5000, null=False, blank=False)
    source = models.TextField(max_length=500, null=False, blank=False)

    def __str__(self):
        return self.source


class TwitterDataRead(models.Model):
    tweet = models.ForeignKey(TwitterData, on_delete=models.CASCADE)
    flag = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        return self.tweet.source


class NewsData(models.Model):
    text = models.TextField(max_length=5000, null=False, blank=False)
    source = models.TextField(max_length=500, null=False, blank=False)


class NewsDataRead(models.Model):
    news = models.ForeignKey(NewsData, on_delete=models.CASCADE)
    flag = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        return self.news.source


class StockData(models.Model):
    symbol = models.TextField(max_length=5000, null=False, blank=False)
    datetime = models.TextField(max_length=5000, null=False, blank=False)
    dimension = models.TextField(max_length=500, null=False, blank=False)

webinterfaceapp/views/login_views.py
from django.contrib.auth.views import LoginView
from django.utils.http import is_safe_url
from django.urls import reverse, reverse_lazy, resolve
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login, logout as auth_logout, authenticate
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.http import HttpResponseRedirect

from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template import loader
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import *
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.db.models.query_utils import Q
from django.shortcuts import redirect

from authentication.forms import SignUpForm
from authentication.models import Profile


class SignIn(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    redirect_url_name = 'financialdataportal:home'
    redirect_url = reverse_lazy(redirect_url_name)
    success_url = redirect_url
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'authentication/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        if request.user.is_authenticated:
            redirect_to = request.POST.get('next', request.GET.get('next', ''))
            # check form validity
            # authenticate user
            if redirect_to and is_safe_url(url=redirect_to, host=request.get_host()):
                return redirect(redirect_to)
            else:
                return HttpResponseRedirect('/?next=home')

        request.session.set_test_cookie()

        return super(SignIn, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(SignIn, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, host=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to

    def get_context_data(self, **kwargs):
        context = super(SignIn, self).get_context_data(**kwargs)
        context['auth_form'] = AuthenticationForm
        login_url_name = 'authentication:sign_in'
        context['login_action'] = reverse(login_url_name)
        return context


class SignOut(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/?next=home'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(SignOut, self).get(request, *args, **kwargs)


# Reset Password
class ResetPasswordRequestView(FormView):

    @staticmethod
    def validate_email_address(email):
        '''
        This method here validates the if the input is an email address or not. Its return type is boolean, True if the input is a email address or False if its not.
        '''

        try:
            validate_email(email)
            return True
        except ValidationError:
            return False

    def post(self, request, *args, **kwargs):
        '''
        A normal post request which takes input from field "email_or_username" (in ResetPasswordRequestForm).
        '''

        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data["email_or_username"]
        if self.validate_email_address(data) is True:  # uses the method written above
            '''
            If the input is an valid email address, then the following code will lookup for users associated with that email address. If found then an email will be sent to the address, else an error message will be printed on the screen.
            '''
            associated_users = User.objects.filter(Q(email=data) | Q(username=data))
            if associated_users.exists():
                for user in associated_users:
                    c = {
                        'email': user.email,
                        'domain': request.META['HTTP_HOST'],
                        'site_name': '127.0.0.1:8000',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    subject_template_name = 'DjangoECommerceApp/Authentication/PasswordReset/password_reset_subject.txt'
                    # copied from django/contrib/admin/templates/registration/password_reset_subject.txt to templates directory
                    email_template_name = 'DjangoECommerceApp/Authentication/PasswordReset/password_reset_email.html'
                    # copied from django/contrib/admin/templates/registration/password_reset_email.html to templates directory
                    subject = loader.render_to_string(subject_template_name, c)
                    # Email subject *must not* contain newlines
                    subject = ''.join(subject.splitlines())
                    email = loader.render_to_string(email_template_name, c)
                    send_mail(subject, email, settings.DEFAULT_FROM_EMAIL, [user.email], fail_silently=False)
                result = self.form_valid(form)
                messages.success(request,
                                 'An email has been sent to ' + data + ". Please check its inbox to continue reseting password.")
                return result
            result = self.form_invalid(form)
            messages.error(request, 'No user is associated with this email address')
            return result
        else:
            '''
            If the input is an username, then the following code will lookup for users associated with that user. If found then an email will be sent to the user's address, else an error message will be printed on the screen.
            '''
            associated_users = User.objects.filter(username=data)
            if associated_users.exists():
                for user in associated_users:
                    c = {
                        'email': user.email,
                        'domain': '127.0.0.1:8000',  # or your domain
                        'site_name': 'example',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    subject_template_name = 'DjangoECommerceApp/Authentication/PasswordReset/password_reset_subject.txt'
                    email_template_name = 'DjangoECommerceApp/Authentication/PasswordReset/password_reset_email.html'
                    subject = loader.render_to_string(subject_template_name, c)
                    # Email subject *must not* contain newlines
                    subject = ''.join(subject.splitlines())
                    email = loader.render_to_string(email_template_name, c)
                    send_mail(subject, email, settings.DEFAULT_FROM_EMAIL, [user.email], fail_silently=False)
                result = self.form_valid(form)
                messages.success(request,
                                 'Email has been sent to ' + data + "'s email address. Please check its inbox to continue reseting password.")
                return result
            result = self.form_invalid(form)
            messages.error(request, 'This username does not exist in the system.')
            return result
        messages.error(request, 'Invalid Input')
        return self.form_invalid(form)


class PasswordResetConfirmView(FormView):

    def post(self, request, uidb64=None, token=None, *arg, **kwargs):
        """
        View that checks the hash in a password reset link and presents a
        form for entering a new password.
        """
        # UserModel = get_user_model()
        form = self.form_class(request.POST)
        assert uidb64 is not None and token is not None  # checked by URLconf
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            if form.is_valid():
                new_password = form.cleaned_data['new_password2']
                user.set_password(new_password)
                user.save()
                messages.success(request, 'Password has been reset.')
                return self.form_valid(form)
            else:
                messages.error(request, 'Password reset has not been unsuccessful.')
                return self.form_invalid(form)
        else:
            messages.error(request, 'The reset password link is no longer valid.')
            return self.form_invalid(form)


class PublicPage(DetailView):
    template_name = 'authentication/profile.html'
    model = Profile

    # def get_context_data(self, **kwargs):

webinterfaceapp/templates/webinterfaceapp/google_search.html
{% extends "./public/dashboardBase.html" %}
{% load static %}

{% block main_content %}

    <script type="text/javascript"
            src="https://ssl.gstatic.com/trends_nrtr/1709_RC01/embed_loader.js"
            xmlns="http://www.w3.org/1999/html"></script>

    <div id="page-wrapper" class="gray-bg">

        {% include 'webinterfaceapp/public/CommonHeadBar.html' %}

        <style type="text/css">
            @media screen and (max-width: 1400px) and (min-width: 800px) {

            }

            @media screen and (max-width: 2000px) and (min-width: 1401px) {

            }

            #loading {
                position: fixed;
                margin: 0 auto;
                width: 20%;
                z-index: 15;
                top: 50%;
                left: 40%;
            }

            .widget {
                margin-bottom: 0px;
                margin-top: 0px;
            }

            #sentiment_trend_id {
                width: 100%;
                height: 500px;
            }
        </style>

        <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-sm-4">
                <h2>Home </h2>
                <ol class="breadcrumb">
                    <li>
                        <a href="{% url 'webinterfaceapp:home' %}">Home</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'webinterfaceapp:google_search_trend' %}"><strong>Google Search
                            Trend</strong></a>
                    </li>
                </ol>
            </div>
            <div class="col-sm-8">

            </div>
        </div>


        <div class="wrapper wrapper-content animated fadeInRight">

            {#  Start :: Top Row containing search text box and positive negative neutral hit count#}
            <div class="row">
                <div class="col-lg-6">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Principal Component Analysis Service</h5>

                            <div class="ibox-tools">
                                <a class="collapse-link">
                                    <i class="fa fa-chevron-up"></i>
                                </a>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <i class="fa fa-wrench"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-user">
                                    <li><a href="#">Config 1</a>
                                    </li>
                                    <li><a href="#">Config 2</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="ibox-content">

                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">
                                    <form method="post" action="{% url 'webinterfaceapp:google_search_trend' %}">
                                        {% csrf_token %}
                                        <div class="form-group row" id="twitter-selected">
                                            <label class="col-md-2  control-label">Search using text</label>
                                            <div class="col-md-10">
                                                <input type="text" name="google-text" id="google-text"
                                                       placeholder="Enter text" class="form-control"
                                                       value="{{ result }}">
                                            </div>
                                        </div>

                                        <div class="form-group row pull-right">
                                            <div class="col-md-12">
                                                <div class="col-md-6">
                                                    <button id="start_analysis"
                                                            class="btn btn-primary pull-right m-t-n-xs"
                                                            name="submit">Submit
                                                    </button>
                                                </div>

                                            </div>

                                        </div>
                                    </form>


                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>


                        </div>
                    </div>


                </div>
                <div class="col-lg-6">
                    <div class="ibox float-e-margins">

                        <div id="first"></div>

                        <div class="ibox-content">

                            <script type="text/javascript">

                                var key = $('#google-text').val();
                                googleTrendsFirst(key);

                                {#$('#start_analysis').click(function () {#}
                                {##}
                                {##}
                                {#    var key = $('#google-text').val();#}
                                {#    console.log(key);#}
                                {##}
                                {#    $.ajax({#}
                                {#        url: "{% url 'webinterfaceapp:google_search' %}",#}
                                {#        type: 'GET',#}
                                {#        dataType: 'json',#}
                                {##}
                                {#        success: function (data) {#}
                                {##}
                                {#            googleTrendsFirst(key);#}
                                {#            googleTrendsSecond(key);#}
                                {##}
                                {#        }#}
                                {#    });#}
                                {##}
                                {##}
                                {# });#}

                                function googleTrendsFirst(key) {


                                    $("#first").remove();
                                    var f = trends.embed.renderExploreWidget("GEO_MAP", {
                                        "comparisonItem": [{
                                            "keyword": key,
                                            "geo": "BD",
                                            "time": "today 12-m"
                                        }], "category": 0, "property": ""
                                    }, {
                                        "exploreQuery": "geo=BD&q=bangla&date=today 12-m",
                                        "guestPath": "https://trends.google.com:443/trends/embed/"
                                    });

                                    $("#first").append(f);


                                }
                            </script>

                        </div>
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="col-md-12">
                    <div class="ibox">


                        <div class="ibox-content">

                            <div id="second"></div>


                            <script type="text/javascript">


                                var key = $('#google-text').val();
                                googleTrendsSecond(key);

                                {#$('#start_analysis').click(function () {#}
                                {##}
                                {##}
                                {#    var key = $('#google-text').val();#}
                                {#    console.log(key);#}
                                {##}
                                {#    googleTrendsSecond(key);#}
                                {##}
                                {##}
                                {##}
                                {# });#}

                                function googleTrendsSecond(key) {
                                    $("#second").remove();
                                    var t = trends.embed.renderExploreWidget("TIMESERIES",
                                        {
                                            "comparisonItem":
                                                [{"keyword": key, "geo": "BD", "time": "today 12-m"}],
                                            "category": 0,
                                            "property": ""
                                        }, {
                                            "exploreQuery": "geo=BD&q=bangla&date=today 12-m",
                                            "guestPath": "https://trends.google.com:443/trends/embed/"
                                        });

                                    $("#second").append(t);

                                }
                            </script>


                        </div>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-4">
                    <div class="ibox">


                        <div class="ibox-content">


                            <script type="text/javascript">

                                googleTrendsThird();

                                function googleTrendsThird() {


                                    trends.embed.renderTopChartsWidget("ff4e31df-19ca-4068-9375-93863bb97e95", {
                                        "geo": "BD",
                                        "guestPath": "https://trends.google.com:443/trends/embed/"
                                    }, 2018);


                                }
                            </script>


                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="ibox">


                        <div class="ibox-content">


                            <script type="text/javascript">


                                googleTrendsFourth();

                                function googleTrendsFourth() {


                                    trends.embed.renderTopChartsWidget("b55e770a-eafd-4fa5-8f83-abadc5be658f", {
                                        "geo": "BD",
                                        "guestPath": "https://trends.google.com:443/trends/embed/"
                                    }, 2018);


                                }
                            </script>


                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="ibox">


                        <div class="ibox-content">


                            <script type="text/javascript">


                                googleTrendsFifth();
                                function googleTrendsFifth() {


                                    trends.embed.renderTopChartsWidget("74635f68-2faf-40f0-8156-ce5c112dcf20", {
                                        "geo": "BD",
                                        "guestPath": "https://trends.google.com:443/trends/embed/"
                                    }, 2018);


                                }
                            </script>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {#    <script type="text/javascript">#}
    {##}
    {##}
    {#        console.log(key);#}
    {#        googleTrendsFirst(key);#}
    {#        googleTrendsSecond(key);#}
    {#        googleTrendsThird(key);#}
    {##}
    {#        $('#start_analysis').click(function () {#}
    {##}
    {##}
    {#            var key = $('#google-text').val();#}
    {#            console.log(key);#}
    {##}
    {#            googleTrendsSecond(key);#}
    {#            googleTrendsThird(key);#}
    {##}
    {##}
    {#        });#}
    {#    </script>#}


{% endblock %}

webinterfaceapp/templates/webinterfaceapp/login.html
{% load static %}

<!DOCTYPE html>
<html>

{% include 'webinterfaceapp/public/CommonHeader.html' %}

<body class="gray-bg" >


{#<div style="background-size: cover;#}
{#    /* height: 100%; */#}
{#    background-repeat: no-repeat;#}
{#    background-image: url(https://memegene.net/sites/default/files/wallpaper/analyst-clipart/486682/analyst-clipart-item-analysis-486682-1504047.jpg);"#}
{#     >#}
    <div class="middle-box text-center loginscreen animated fadeInDown" >
        <div>
            <div>
                <h1 class="logo-name"><a href="{% url 'webinterfaceapp:home' %}">PCA</a></h1>
            </div>
            <h3>Welcome to Principal Component Analysis</h3>
            <p>Please provide your credentials to look into dashboards</p>

            {% if message is not None %}
                <div class="alert alert-danger">
                    <strong>Danger!</strong> {{ message }}
                </div>
            {% endif %}

            <form class="form-horizontal" method="post" enctype="multipart/form-data" action="{% url 'webinterfaceapp:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="userid" class="form-control" placeholder="Username" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="Password" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                <a href="#"><small>Forgot password?</small></a>
                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="{% url 'webinterfaceapp:register' %}">Create an account</a>
            </form>


            <p class="m-t"> <small>Powered By BUET. All rights reserved &copy; 2019</small> </p>
        </div>
    </div>
{#</div>#}
    {% include 'webinterfaceapp/public/CommonFooter.html' %}

    <!-- Mainly scripts -->
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

</body>


</html>

webinterfaceapp/templates/webinterfaceapp/register.html
{% load static %}

<!DOCTYPE html>
<html>

{% include 'webinterfaceapp/public/CommonHeader.html' %}

<body class="gray-bg">

    <div class="middle-box text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name"><a href="{% url 'webinterfaceapp:home' %}">PCA</a></h1>

            </div>
            <h3>Register Here...</h3>
            <p>Create account to see it in action.</p>
            <form class="m-t" role="form" action="{% url 'webinterfaceapp:home' %}">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Name" required="">
                </div>
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="Email" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" required="">
                </div>
                <div class="form-group">
                        <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> Agree the terms and policy </label></div>
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Register</button>

                <p class="text-muted text-center"><small>Already have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="login.html">Login</a>
            </form>
{#            <p class="m-t"> <small>skmslk &copy; 2019</small> </p>#}


        </div>
    </div>
    {% include 'webinterfaceapp/public/CommonFooter.html' %}

    <!-- Mainly scripts -->
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="js/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
</body>

</html>